[target.bmvm.json]
rustflags = "-Clink-arg=-Tlayout.x -Crelocation-model=static -Ctarget-cpu=native"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = "-Clink-arg=-Tlayout.x -Crelocation-model=static -Ctarget-cpu=native"
